# Generated by Django 5.1.2 on 2024-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='start_of_week',
            field=models.DateField(default='2024-10-21'),
            preserve_default=False,
        ),
    ]
