# Generated by Django 5.1.2 on 2024-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
