# Generated by Django 5.1.2 on 2024-10-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="code",
        ),
        migrations.AddField(
            model_name="project",
            name="sequence_numbercode",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
