# Generated by Django 5.1.2 on 2024-10-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_remove_project_code_project_sequence_numbercode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="project",
            name="sequence_numbercode",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
