# Generated by Django 5.1.2 on 2024-10-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_project_name_alter_project_sequence_numbercode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="businessunit",
        ),
    ]
